In [1]:
import pandas as pd
import numpy as np

df_join_4 = pd.read_csv('2d_data.csv')

# group the dataframe by the 'group' column
groups = df_join_4.groupby('fips')

# create a 3D numpy array from the groups
array_block = np.array([group_df.values for _, group_df in groups])
array_block = array_block.transpose((1,2,0))
# print the resulting 3D array
display(array_block.shape)

/var/folders/8v/b1l_n51d2_b4pkp_5kxnxwhh0000gn/T/ipykernel_4139/1126663046.py:4: DtypeWarning: Columns (5,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df_join_4 = pd.read_csv('2d_data.csv')


(47, 34, 3143)

In [2]:
two_d_df = pd.read_csv('2d_data.csv')
two_d_df.columns

/var/folders/8v/b1l_n51d2_b4pkp_5kxnxwhh0000gn/T/ipykernel_4139/4090279209.py:1: DtypeWarning: Columns (5,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  two_d_df = pd.read_csv('2d_data.csv')


Index(['Unnamed: 0', 'Date', 'fips', 'year', 'month', 'state_alpha',
       'rent_50_0', 'rent_50_1', 'rent_50_2', 'rent_50_3', 'rent_50_4',
       'Coastline_Region', 'coastline_flag',
       'Top_Marginal_Personal_Income_Tax_Rate',
       'Top_Marginal_Corporate_Income_Tax_Rate',
       'Personal_Income_Tax_Progressivity_(change in tax liability per $1,000 of income)',
       'Property_Tax_Burden_(per $1,000 of personal income)',
       'Sales_Tax_Burden(per $1,000 of personal income)',
       'Remaining_Tax_Burden(per $1,000 of personal income)',
       'Estate_Inheritance_Tax_Levied_Flag', 'Recently_Legislated_Tax_Changes',
       'Debt_Service_as_a_Share_of_Tax_Revenue',
       'Public_Employees_Per_10,000_of_Population_(full-time equivalent)',
       'State_Liability_System_Survey_(tort litigation treatment, judicial impartiality, etc.)',
       'State_Minimum_Wage_(federal floor is $7.25)',
       'Average Workers_Compensation_Costs_(per $100 of payroll)',
       'Right-to-Work_

In [3]:
leon_cfips_list = array_block[0,2,:].tolist()

In [4]:
# fill in the missing leading 0 for the fips
leon_cfips_list = [str(int(fips)).zfill(5) for fips in leon_cfips_list]
leon_cfips_list

['01001',
 '01003',
 '01005',
 '01007',
 '01009',
 '01011',
 '01013',
 '01015',
 '01017',
 '01019',
 '01021',
 '01023',
 '01025',
 '01027',
 '01029',
 '01031',
 '01033',
 '01035',
 '01037',
 '01039',
 '01041',
 '01043',
 '01045',
 '01047',
 '01049',
 '01051',
 '01053',
 '01055',
 '01057',
 '01059',
 '01061',
 '01063',
 '01065',
 '01067',
 '01069',
 '01071',
 '01073',
 '01075',
 '01077',
 '01079',
 '01081',
 '01083',
 '01085',
 '01087',
 '01089',
 '01091',
 '01093',
 '01095',
 '01097',
 '01099',
 '01101',
 '01103',
 '01105',
 '01107',
 '01109',
 '01111',
 '01113',
 '01115',
 '01117',
 '01119',
 '01121',
 '01123',
 '01125',
 '01127',
 '01129',
 '01131',
 '01133',
 '02013',
 '02016',
 '02020',
 '02050',
 '02060',
 '02068',
 '02070',
 '02090',
 '02100',
 '02105',
 '02110',
 '02122',
 '02130',
 '02150',
 '02164',
 '02170',
 '02180',
 '02185',
 '02188',
 '02195',
 '02198',
 '02220',
 '02230',
 '02240',
 '02261',
 '02270',
 '02275',
 '02282',
 '02290',
 '04001',
 '04003',
 '04005',
 '04007',


In [5]:
dtypes = {'cfips': str}
cfips_df = pd.read_csv('cfips.csv', dtype=dtypes)

In [6]:
zzp_cfips_list = cfips_df['cfips'].tolist()

In [7]:
data_block = np.ones((47, 34, 3142)) * np.nan
data_block = data_block.astype('object')

for i, fips in enumerate(leon_cfips_list):
    if fips == zzp_cfips_list[i-2]:
        data_block[:,:,i-2] = array_block[:,:,i-2]
    elif fips == zzp_cfips_list[i-1]:
        data_block[:,:,i-1] = array_block[:,:,i-1]
    elif fips == zzp_cfips_list[i]:
        data_block[:,:,i] = array_block[:,:,i]
    elif fips == zzp_cfips_list[i+1]:
        data_block[:,:,i+1] = array_block[:,:,i+1]
    elif fips == zzp_cfips_list[i+2]:
        data_block[:,:,i+2] = array_block[:,:,i+2]
    else:
        print(fips)

02270
46113
51515


In [8]:
data_block.shape

(47, 34, 3142)

In [9]:
data_block[0,2,:]

array([1001, 1003, 1005, ..., 56039, 56041, 56043], dtype=object)

In [10]:
# shown the index of the nan values
np.argwhere(np.isnan(data_block[0,2,:].astype(float)))

array([[  81],
       [2412]])

In [11]:
zzp_cfips_list[81], zzp_cfips_list[2412]

('02158', '46102')

In [12]:
data_block[0,2,:][80], data_block[0,2,:][81], data_block[0,2,:][82]

(2150, nan, 2170)

In [13]:
data_block[0,2,:][2411], data_block[0,2,:][2412], data_block[0,2,:][2413]

(46101, nan, 46105)

In [14]:
data_block[0,2,81] = 2158
data_block[0,2,2412] = 46102

In [15]:
data_block.shape

(47, 34, 3142)

In [16]:
data_block.astype('object')

array([[[0, 1, 2, ..., 3139, 3140, 3141],
        ['2019-08-31', '2019-08-31', '2019-08-31', ..., '2019-08-31',
         '2019-08-31', '2019-08-31'],
        [1001, 1003, 1005, ..., 56039, 56041, 56043],
        ...,
        ['2019-08-01', '2019-08-01', '2019-08-01', ..., '2019-08-01',
         '2019-08-01', '2019-08-01'],
        [3.0076818, 7.2391562, 1.0731378, ..., 26.433363, 4.6120157,
         2.603246],
        [1249.0, 11464.0, 222.0, ..., 4887.0, 674.0, 162.0]],

       [[3143, 3144, 3145, ..., 6282, 6283, 6284],
        ['2019-09-30', '2019-09-30', '2019-09-30', ..., '2019-09-30',
         '2019-09-30', '2019-09-30'],
        [1001, 1003, 1005, ..., 56039, 56041, 56043],
        ...,
        ['2019-09-01', '2019-09-01', '2019-09-01', ..., '2019-09-01',
         '2019-09-01', '2019-09-01'],
        [2.8848701, 7.2909365, 0.99579448, ..., 26.611856, 4.338306,
         2.683593],
        [1198.0, 11546.0, 206.0, ..., 4920.0, 634.0, 167.0]],

       [[6286, 6287, 6288, ..., 9425,

In [17]:
data_block[:,0,:]

array([[0, 1, 2, ..., 3139, 3140, 3141],
       [3143, 3144, 3145, ..., 6282, 6283, 6284],
       [6286, 6287, 6288, ..., 9425, 9426, 9427],
       ...,
       [138292, 138293, 138294, ..., 141431, 141432, 141433],
       [141435, 141436, 141437, ..., 144574, 144575, 144576],
       [144578, 144579, 144580, ..., 147717, 147718, 147719]],
      dtype=object)

In [18]:
data_block = data_block[:,1:,:]

In [19]:
data_block.shape

(47, 33, 3142)

In [20]:
data_block[:,1,:]

array([[1001, 1003, 1005, ..., 56039, 56041, 56043],
       [1001, 1003, 1005, ..., 56039, 56041, 56043],
       [1001, 1003, 1005, ..., 56039, 56041, 56043],
       ...,
       [1001, 1003, 1005, ..., 56039, 56041, 56043],
       [1001, 1003, 1005, ..., 56039, 56041, 56043],
       [1001, 1003, 1005, ..., 56039, 56041, 56043]], dtype=object)

In [21]:
data_block[:,1,:] = np.array(zzp_cfips_list)

In [22]:
data_block[:,1,:]

array([['01001', '01003', '01005', ..., '56041', '56043', '56045'],
       ['01001', '01003', '01005', ..., '56041', '56043', '56045'],
       ['01001', '01003', '01005', ..., '56041', '56043', '56045'],
       ...,
       ['01001', '01003', '01005', ..., '56041', '56043', '56045'],
       ['01001', '01003', '01005', ..., '56041', '56043', '56045'],
       ['01001', '01003', '01005', ..., '56041', '56043', '56045']],
      dtype=object)

In [23]:
features = ['Date', 'fips', 'year', 'month', 'state_alpha',
       'rent_50_0', 'rent_50_1', 'rent_50_2', 'rent_50_3', 'rent_50_4',
       'Coastline_Region', 'coastline_flag',
       'Top_Marginal_Personal_Income_Tax_Rate',
       'Top_Marginal_Corporate_Income_Tax_Rate',
       'Personal_Income_Tax_Progressivity_(change in tax liability per $1,000 of income)',
       'Property_Tax_Burden_(per $1,000 of personal income)',
       'Sales_Tax_Burden(per $1,000 of personal income)',
       'Remaining_Tax_Burden(per $1,000 of personal income)', 
       'Estate_Inheritance_Tax_Levied_Flag', 'Recently_Legislated_Tax_Changes', 
       'Debt_Service_as_a_Share_of_Tax_Revenue',
       'Public_Employees_Per_10,000_of_Population_(full-time equivalent)',
       'State_Liability_System_Survey_(tort litigation treatment, judicial impartiality, etc.)',
       'State_Minimum_Wage_(federal floor is $7.25)',
       'Average Workers_Compensation_Costs_(per $100 of payroll)',
       'Right-to-Work_State_Flag_(option to join or support a union)',
       'Tax_Expenditure_Limits', 'row_id', 'county', 'State_Name',
       'first_day_of_month', 'microbusiness_density', 'active']

In [24]:
data_block[0,:,0]

array(['2019-08-31', '01001', 2019, 8, 'AL', 631.0, 742.0, 890.0, 1133.0,
       1558.0, nan, 0, 0.04, 0.06, -1.8, 14.37, 26.04, 20.87, 0.0, 0.55,
       0.06, 583.5, 65.6, 7.25, 1.33, 1.0, 0.0, '1001_2019-08-01',
       'Autauga County', 'Alabama', '2019-08-01', 3.0076818, 1249.0],
      dtype=object)

In [25]:
# 
data_block = data_block[:,0:-6,:]
data_block[0,:,0]

array(['2019-08-31', '01001', 2019, 8, 'AL', 631.0, 742.0, 890.0, 1133.0,
       1558.0, nan, 0, 0.04, 0.06, -1.8, 14.37, 26.04, 20.87, 0.0, 0.55,
       0.06, 583.5, 65.6, 7.25, 1.33, 1.0, 0.0], dtype=object)

In [26]:
data_block[0,:,0]

array(['2019-08-31', '01001', 2019, 8, 'AL', 631.0, 742.0, 890.0, 1133.0,
       1558.0, nan, 0, 0.04, 0.06, -1.8, 14.37, 26.04, 20.87, 0.0, 0.55,
       0.06, 583.5, 65.6, 7.25, 1.33, 1.0, 0.0], dtype=object)

In [27]:
date_year_month = data_block[:,0,0]
date_year_month = [str(date)[:7] for date in date_year_month]
date_year_month = np.array(date_year_month).reshape(47,1)
date_year_month_repeat = np.repeat(date_year_month, 3142, axis=1)
data_block[:,0,:] = date_year_month_repeat

In [28]:
data_block[0,:,0]

array(['2019-08', '01001', 2019, 8, 'AL', 631.0, 742.0, 890.0, 1133.0,
       1558.0, nan, 0, 0.04, 0.06, -1.8, 14.37, 26.04, 20.87, 0.0, 0.55,
       0.06, 583.5, 65.6, 7.25, 1.33, 1.0, 0.0], dtype=object)

In [29]:
data_block.shape

(47, 27, 3142)

In [30]:
# get rid of the 2, 3, 4th column
data_block = data_block[:,[0,1,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],:]
data_block[0,:,0]

array(['2019-08', '01001', 631.0, 742.0, 890.0, 1133.0, 1558.0, 0, 0.04,
       0.06, -1.8, 14.37, 26.04, 20.87, 0.0, 0.55, 0.06, 583.5, 65.6,
       7.25, 1.33, 1.0, 0.0], dtype=object)

In [31]:
feature_list = ['Date', 'fips', 
       'prev_yr_rent_50_0', 'prev_yr_rent_50_1', 'prev_yr_rent_50_2', 
       'prev_yr_rent_50_3', 'prev_yr_rent_50_4',
       'coastline_flag',
       'Top_Marginal_Personal_Income_Tax_Rate',
       'Top_Marginal_Corporate_Income_Tax_Rate',
       'Personal_Income_Tax_Progressivity_(change in tax liability per $1,000 of income)',
       'Property_Tax_Burden_(per $1,000 of personal income)',
       'Sales_Tax_Burden(per $1,000 of personal income)',
       'Remaining_Tax_Burden(per $1,000 of personal income)',
       'Estate_Inheritance_Tax_Levied_Flag', 'Recently_Legislated_Tax_Changes',
       'Debt_Service_as_a_Share_of_Tax_Revenue',
       'Public_Employees_Per_10,000_of_Population_(full-time equivalent)',
       'State_Liability_System_Survey_(tort litigation treatment, judicial impartiality, etc.)',
       'State_Minimum_Wage_(federal floor is $7.25)',
       'Average Workers_Compensation_Costs_(per $100 of payroll)',
       'Right-to-Work_State_Flag_(option to join or support a union)',
       'Tax_Expenditure_Limits']

print(data_block.shape)
print(len(feature_list))


(47, 23, 3142)
23


In [32]:
data_description = {}
for i, feature in enumerate(feature_list):
    data_description[f'feature_{i}'] = feature

In [33]:
data_description

{'feature_0': 'Date',
 'feature_1': 'fips',
 'feature_2': 'prev_yr_rent_50_0',
 'feature_3': 'prev_yr_rent_50_1',
 'feature_4': 'prev_yr_rent_50_2',
 'feature_5': 'prev_yr_rent_50_3',
 'feature_6': 'prev_yr_rent_50_4',
 'feature_7': 'coastline_flag',
 'feature_8': 'Top_Marginal_Personal_Income_Tax_Rate',
 'feature_9': 'Top_Marginal_Corporate_Income_Tax_Rate',
 'feature_10': 'Personal_Income_Tax_Progressivity_(change in tax liability per $1,000 of income)',
 'feature_11': 'Property_Tax_Burden_(per $1,000 of personal income)',
 'feature_12': 'Sales_Tax_Burden(per $1,000 of personal income)',
 'feature_13': 'Remaining_Tax_Burden(per $1,000 of personal income)',
 'feature_14': 'Estate_Inheritance_Tax_Levied_Flag',
 'feature_15': 'Recently_Legislated_Tax_Changes',
 'feature_16': 'Debt_Service_as_a_Share_of_Tax_Revenue',
 'feature_17': 'Public_Employees_Per_10,000_of_Population_(full-time equivalent)',
 'feature_18': 'State_Liability_System_Survey_(tort litigation treatment, judicial imparti

In [34]:
import pickle
import json

data_name = 'leon_data'

# save data in pickle format
with open(f'BLOCKED_{data_name}_data.pkl', 'wb') as f:
    pickle.dump(data_block, f)

# save data in json format
with open(f'BLOCKED_{data_name}_data_description.json', 'w') as f:
    json.dump(data_description, f)

In [35]:
data_block[:,2,0]

array([631.0, 631.0, 631.0, 631.0, 631.0, 620.0, 620.0, 620.0, 620.0,
       620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 615.0,
       615.0, 615.0, 615.0, 615.0, 615.0, 615.0, 615.0, 615.0, 615.0,
       615.0, 615.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0,
       685.0, 685.0, 685.0, 685.0, 685.0, 687.0, 687.0, 687.0, 687.0,
       687.0, 687.0], dtype=object)

In [36]:
data_block[0,:,0]

array(['2019-08', '01001', 631.0, 742.0, 890.0, 1133.0, 1558.0, 0, 0.04,
       0.06, -1.8, 14.37, 26.04, 20.87, 0.0, 0.55, 0.06, 583.5, 65.6,
       7.25, 1.33, 1.0, 0.0], dtype=object)